name: Update Filtered EPG

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (UTC)
  workflow_dispatch:        # allows manual run from Actions UI

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run EPG Filter
        run: python filter_epg.py

      - name: Commit and push filtered EPG gzip
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add filtered_epg.xml.gz
          git commit -m "Update filtered EPG gzip" || echo "No changes to commit"
          git push
