name: Update M3U and EPG

on:
  workflow_dispatch:
  schedule:
    - cron: "*/2 * * * *"  # Every 2 minutes
    - cron: "0 */6 * * *"  # Every 6 hours

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install requests rapidfuzz

      - name: Run update script
        run: python update_m3u_epg.py

      - name: Commit and push changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add updated_playlist.m3u combined_epg.xml.gz
          git commit -m "Auto update M3U & EPG"
          git push
